export const NODE_ENV = "NODE_ENV";

export const PORT = "PORT";

export const MONGODB_URI = "MONGODB_URI";

export const EXCHANGE_NAME = "_event";

export const REDIS_CLOUD_URL = "REDIS_CLOUD_URL";

export const RABBITMQ_URL = "RABBITMQ_URL";

export const CLOUDINARY_CLOUD_NAME = "CLOUDINARY_CLOUD_NAME";

export const CLOUDINARY_API_KEY = "CLOUDINARY_API_KEY";

export const CLOUDINARY_API_SECRET = "CLOUDINARY_API_SECRET";

export const JWT_ACCESS_TOKEN_SECRET = "JWT_ACCESS_TOKEN_SECRET";

export const JWT_ACCESS_TOKEN_EXP = "JWT_ACCESS_TOKEN_EXP";

export const JWT_REFRESH_TOKEN_SECRET = "JWT_REFRESH_TOKEN_SECRET";

export const JWT_REFRESH_TOKEN_EXP = "JWT_REFRESH_TOKEN_EXP";
